#数据库配置
spring:
    datasource:
        name: ebus
        url: jdbc:mysql://10.1.10.76:3306/ebus?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
        username: dev
        password: 123456
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver


#MyBatis配置
mybatis:
    type-aliases-package: com.lantaiyuan.ebus.model
    mapper-locations: classpath:mapping/*.xml

#kafka配置
kafka: 
  bootstrap: 
    servers: 10.1.10.78:9092,10.1.10.84:9092,10.1.10.85:9092
  session: 
    timeout-ms: 30000 
  auto-commit:
    enable: true
    interval-ms: 1000
  auto-offset: 
    reset: latest
  group: 
    id: relRouteBus
  topic: 
    city-code: gw2app-baoji:610300|gw2app-kaiping:440783
    jpushTopic: jpush
    od-topic: odPos
    
#定时器配置
task: 
  #若30分钟没有付款则更改订单表的状态为订单失效
  updateOrderStatus2Invalid: 0/5 * * * * ?
  #定时器实现车票是否提供给用户购买的状态修改（每天凌晨12点执行一次,小于当前日期且isOpenToBuy=1的票改为isOpenToBuy=0（不开放购买）
  updateTickcetStatusBeforeNow: 0 0 0 * * ?
  #清空用户上车提醒动态表JPUSH_ALREADY_ALERT_DYNAMIC（每天凌晨12点执行一次）
  clearTheDataOfAlreadyAlert: 0 0 0 * * ?
  #清空用户下车提醒动态表中已经提醒过的数据（每天凌晨12点执行一次）
  clearTheDataInLeavingCarAlert: 0 0 0 * * ?
  #开放购买下个月的票(每月27号执行一次)
  updateTickcetStatusNextMonth: 0 0 0 27 * ?
  #用户当前日期之前且票状态为1（有效）-*代表其未乘车* 的车票，状态改为3(过期)
  modifyTickcetStatusToExpired: 0 0/30 * * * ?
  #用户若10分钟没有付款 ,车票订单则更改,订单表的状态为3-订单失效
  modifyUnPaidTickcetOrderStatus: 0 0/10 * * * ?
  #用户若60分钟没有付款 ,周边游订单则更改订单失效，票池重新计算
  modifyUnPaidTravelOrderStatus: 0 0/5 * * * ?

#日志配置     
logging:
    level:
      root: INFO
      com:
        lantaiyuan:
          ebus:
            mapper: TRACE
      org: 
        springframework: 
          scheduling: INFO